name: Deploy AWS CDK

on:
  push:
  branches: [ feat/cdk ]
  pull_request:
  branches: [ feat/cdk ]

  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-1

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install Requirements
        run: 'pip3 install -r requirements.txt'
        working-directory: cdk

      - name: CDK Synth
        run: cdk synth
        working-directory: cdk

      - name: CDK Deploy
        run: cdk deploy
        working-directory: cdk
